Dia_eaties_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('diaeaties2app.urls'), name='diaeaties2app_urls'),
    path('accounts/', include('allauth.urls')),
]

diaeaties2app/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('contact/', views.contact, name='contact'),
    path('my_profile/', views.Profile.as_view(), name='profile'),
    path('create-recipe/', views.CreateRecipe.as_view(), name='create_recipe'),
    path('<slug:slug>/delete/', views.DeleteRecipe.as_view(), name='delete'),
    path('<slug:slug>/update/', views.UpdateRecipe.as_view(), name='update'),
    path('about', views.RecipeList.as_view(template_name="about.html"),
         name="about"),
    path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('love/<slug:slug>/', views.LovedRecipe.as_view(),
         name='loved_recipe'),
]

diaeaties2app/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))


class Recipe(models.Model):
    recipe_name = models.CharField(max_length=195, unique=True)
    slug = models.SlugField(max_length=195, unique=True)
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="main_posts"
    )
    recipe_image = CloudinaryField('image', default='placeholder')
    highlight = models.TextField(blank=True)
    about = models.TextField(blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    loves = models.ManyToManyField(
        User, related_name='main_loves', blank=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.recipe_name

    def number_of_loves(self):
        return self.loves.count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.recipe_name)
        super(Recipe, self).save(*args, **kwargs)


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name="comments")
    display_name = models.CharField(max_length=125)
    email = models.EmailField()
    comment_text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return f"Comment {self.comment_text} by {self.display_name}"


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    sent = models.DateTimeField(auto_now_add=True)
    message = models.TextField(max_length=500)

    def __str__(self):
        return f'{self.email}'

diaeaties2app/forms.py
from .models import Comment, Contact, Recipe
from django_summernote.widgets import SummernoteWidget
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text',)


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        exclude = ('slug', 'creator', 'updated_on', 'shared_on', 'loves',)
        widgets = {
            'content': SummernoteWidget(),
            'about': SummernoteWidget()
        }

diaeaties2app/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Recipe
from .forms import CommentForm, ContactForm, RecipeForm


class RecipeList(generic.ListView):
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created')
    template_name = 'index.html'
    paginate_by = 2


class RecipeDetail(View):
    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('created')
        loved = False
        if recipe.loves.filter(id=self.request.user.id).exists():
            loved = True

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": False,
                "loved": loved,
                "comment_form": CommentForm(),
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('created')
        loved = False
        if recipe.loves.filter(id=self.request.user.id).exists():
            loved = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.display_name = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": True,
                "loved": loved,
                "comment_form": CommentForm()
            },
        )


class LovedRecipe(View):
    def post(self, request, slug, *args, **kwargs):
        recipe = get_object_or_404(Recipe, slug=slug)
        if recipe.loves.filter(id=request.user.id).exists():
            recipe.loves.remove(request.user)
        else:
            recipe.loves.add(request.user)

        return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


"""Displays the contact form"""


def contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, 'Thank you for contacting us!')
            return redirect('home')

    contact_form = ContactForm()
    context = {'contact_form': contact_form}
    return render(request, 'contact.html', context)


class CreateRecipe(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'create_recipe.html'
    success_message = "Thank you for submitting your recipe dia-buddy"

    def get_success_url(self):
        return reverse('recipe_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        form.instance.creator = self.request.user
        print(form.cleaned_data)
        return super().form_valid(form)


class UpdateRecipe(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'update_recipe.html'
    success_message = "You have successfully updated your recipe!"

    def get_success_url(self):
        return reverse('recipe_detail', kwargs={'slug': self.object.slug})


class DeleteRecipe(LoginRequiredMixin, DeleteView):
    """Delete a recipe"""
    model = Recipe
    template_name = 'delete_recipe.html'
    success_url = reverse_lazy("home")


class Profile(View):
    """
    Display recipes created by user as draft and published,
    and the ones they have hit the love button for
    """

    def get(self, request, *args, **kwargs):
        published = Recipe.objects.filter(status=1, creator=request.user)
        drafts = Recipe.objects.filter(status=0, creator=request.user)
        this_user = request.user
        loves = User.objects.get(pk=this_user.id).main_loves.all()

        return render(
            request,
            'profile.html',
            {
                'published': published,
                'drafts': drafts,
                'loves': loves,
            },
        )

templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="overlay"></div>
<div class="container  container-override">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2  center-button">
            <span class="nav-title">Dia</span><span>-eaties</span>
            <br>
            {% if not user.is_authenticated%}
            <a class="btn btn-signup right" href="{% url 'account_signup' %}">Join Us</a>
            {% endif %}
            <div class="about-container">
                <div class="about-text">
                    <div>
                        <p>Welcome to Dia-eaties,</p>
                        <p style="line-height: 220%;">Here at Dia-eaties our goal is to improve the health of diabetics one bolus at a time. Diabetes is a difficult and  often lonley condition, but not anymore! Together we are going to build a community of Dia-eaters, so join us and keep chasing that unicorn.</p>
                        <p style="font-family: Indie Flower, sans-serif; font-size: 2rem;">Love Dia-eaties</p>
                        <img src="https://res.cloudinary.com/diabekki/image/upload/v1635610261/pexels-polina-tankilevitch-5469165_up4fb5.jpg" alt="Cloundinary image"
                            width="100%" style="border-radius: 15px 50px 30px;">
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Dia-Eaties</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="A diabetic friendly website where users can create, share and save recipes.">
    <meta name="keywords" content="recipes, recipe blog, diabetes, diabetics, unicorn, bolus">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Roboto:wght@300&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="nav-title">Dia</span><span>-eaties</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-contact" href="{% url 'contact' %}">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link nav-contact" href="{% url 'create_recipe' %}">Create Recipe</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">My Profile</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text">
                    Type 1 of a kind
                </span>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3">
        <p class="m-0 text-center footer-text">Rebecca Tubridy</p>
        <p class="m-0 text-center footer-text">Copyright 2021
            <a href="https://github.com/diabekki" target=”_blank”><i class="fab fa-github-square footer-text"></i></a>
    </footer>
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 1925);
    </script>
</body>

</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container  container-override">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Contact Us</h3>

            <p>Do you have any questions or queries? Please do not hesitate to contact us
                directly.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" style="margin-top: 1.3em;">
                {{ contact_form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-signup right" style="margin-top: 5px;">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/create_recipe.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container  container-override">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Create new recipe</h3>

            <p>Don't use this form on mobile or tablet</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" enctype="multipart/form-data" style="margin-top: 1.3em;">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-signup right" style="margin-top: 5px;">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/delete_recipe.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="overlay"></div>
<div class="container container-override">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" >{% csrf_token %}
                <h1>Delete Recipe?</h1>
                <br><br>
                <h3>Are you sure you want to delete the following recipe:"<span style="font-weight: 900;">{{ object }}</span>"?</h3>
                <br><br>
                 
                    <input type="submit" value="Confirm" class="btn btn-signup">
                    <input type=button value="Cancel"  class="btn btn-signup" onClick="javascript:history.go(-1);">
                </form>
        </div>
    </div>
</div>




{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Recipe Entries Column -->
        <div class="col-12 mt-3">
            <div class="row d-flex justify-content-around">
                {% for recipe in recipe_list %}
                {% if recipe.status == 1 %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.recipe_image.url %}
                                <img class="card-img-top" alt="Diabetes ribbon"
                                    src="https://res.cloudinary.com/diabekki/image/upload/v1635610273/pexels-pavel-danilyuk-7653347_1_dzj4ii.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.recipe_image.url }}" alt="user uploaded image">
                                {% endif %}
                            </div>
                            <div class="author">
                                <p class="author">Author: {{ recipe.creator }}</p>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="post-link">
                                <h2 class="card-title">{{ recipe.recipe_name }}</h2>
                                <p class="card-text">{{ recipe.highlight }}</p>
                            </a>
                            <hr />
                            <p class="card-text h6" style="color: #5B89C7;">{{ recipe.created}} <i
                                    class="far fa-heart"></i>
                                {{ recipe.number_of_loves }}</p>
                            {% if user.is_authenticated and user == recipe.creator %}
                            <a href="{% url 'update' recipe.slug %}" class="btn-update btn" role="button">Update</a>
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% elif user.is_superuser %}
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row">
                {% endif %}
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/landing_page.html
{% extends "base.html" %}

{% block content %}

<div class="overlay"></div>
<div class="container  container-override">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2  center-button">
            <h3>Dia-Eaties<span><img src="" alt="" class=""></span></h3>

            <p>Welcome!</p>
            <p></p>
            <a class="btn btn-signup right" href="{% url 'index' %}">View Blog</a>
        </div>
    </div>
</div>
{%endblock%}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1>PROFILE</h1>
<br>

<div class="container">
    <h2 class="fs-3">Published Recipes</h2>

    <div class="row">

        <div class="col-12 mt-3 left">
            <div class="row">

                {% for recipe in published %}

                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.recipe_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/diabekki/image/upload/v1635610273/pexels-pavel-danilyuk-7653347_1_dzj4ii.jpg"
                                    alt="Cloudinary Image">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.recipe_image.url }}">
                                {% endif %}
                                <div class="author">
                                    <p class="author">Author: {{ recipe.creator }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="post-link">
                                <h2 class="card-title">{{ recipe.recipe_name }}</h2>
                                <p class="card-text">{{ recipe.highlight }}</p>
                            </a>
                            <hr />
                            <p class="card-text h6" style="color: #5B89C7;">{{ recipe.created}} <i
                                    class="far fa-heart"></i>
                                {{ recipe.number_of_loves }}</p>
                            {% if user.is_authenticated and user == recipe.creator %}
                            <a href="{% url 'update' recipe.slug %}" class="btn-update btn" role="button">Update</a>
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% elif user.is_superuser %}
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>

                {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row">
                {% endif %}
                {% empty %}
                <p class="empty-text">You have no recipes published </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<br>

<div class="container">
    <h2 class="fs-3">Draft Recipes</h2>


    <div class="row">

        <div class="col-12 mt-3 left">
            <div class="row">

                {% for recipe in drafts %}

                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.recipe_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/diabekki/image/upload/v1635610273/pexels-pavel-danilyuk-7653347_1_dzj4ii.jpg"
                                    alt="Cloudinary Image">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.recipe_image.url }}">
                                {% endif %}
                                <div class="author">
                                    <p class="author">Author: {{ recipe.creator }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="post-link">
                                <h2 class="card-title">{{ recipe.recipe_name }}</h2>
                                <p class="card-text">{{ recipe.highlight }}</p>
                            </a>
                            <hr />
                            <p class="card-text h6" style="color: #5B89C7;">{{ recipe.created}} <i
                                    class="far fa-heart"></i>
                                {{ recipe.number_of_loves }}</p>
                            {% if user.is_authenticated and user == recipe.creator %}
                            <a href="{% url 'update' recipe.slug %}" class="btn-update btn" role="button">Update</a>
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% elif user.is_superuser %}
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row">
                {% endif %}
                {% empty %}
                <p class="empty-text">You have no recipes saved as a draft </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<br>

<div class="container">
    <h2 class="fs-3">Recipes that I love</h2>
    <div class="row">


        <div class="col-12 mt-3 left">
            <div class="row">

                {% for recipe in loves %}

                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.recipe_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/diabekki/image/upload/v1635610273/pexels-pavel-danilyuk-7653347_1_dzj4ii.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.recipe_image.url }}">
                                {% endif %}
                                <div class="author">
                                    <p class="author">Author: {{ recipe.creator }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="post-link">
                                <h2 class="card-title">{{ recipe.recipe_name }}</h2>
                                <p class="card-text">{{ recipe.highlight }}</p>
                            </a>
                            <hr />
                            <p class="card-text h6" style="color: #5B89C7;">{{ recipe.created}} <i
                                    class="far fa-heart"></i>
                                {{ recipe.number_of_loves }}</p>
                            {% if user.is_authenticated and user == recipe.creator %}
                            <a href="{% url 'update' recipe.slug %}" class="btn-update btn" role="button">Update</a>
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% elif user.is_superuser %}
                            <a href="{% url 'delete' recipe.slug %}" class="btn-delete btn" role="button">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row">
                {% endif %}
                {% empty %}
                <p class="empty-text">You have no recipes favourited </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/update_recipe.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container  container-override">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Update recipe</h3>

            <p>Don't use this form on mobile or tablet</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" enctype="multipart/form-data" style="margin-top: 1.3em;">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-signup right" style="margin-top: 5px;">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}